#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("lessons.Resource", IsApplication=true)]

namespace lessons
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040001
			public const int group_codes = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int groups = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int teachers = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int teachers_codes = 2130968579;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_overflow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06004a
			public const int bells = 2131099722;
			
			// aapt resource value: 0x7f060047
			public const int calendar = 2131099719;
			
			// aapt resource value: 0x7f06003d
			public const int datePicker = 2131099709;
			
			// aapt resource value: 0x7f060045
			public const int dateSelectType = 2131099717;
			
			// aapt resource value: 0x7f060035
			public const int linearLayout1 = 2131099701;
			
			// aapt resource value: 0x7f060038
			public const int main = 2131099704;
			
			// aapt resource value: 0x7f060048
			public const int overflow = 2131099720;
			
			// aapt resource value: 0x7f060046
			public const int picker = 2131099718;
			
			// aapt resource value: 0x7f06003e
			public const int rasp = 2131099710;
			
			// aapt resource value: 0x7f060000
			public const int scrollView1 = 2131099648;
			
			// aapt resource value: 0x7f06003f
			public const int scrollView2 = 2131099711;
			
			// aapt resource value: 0x7f060049
			public const int settings = 2131099721;
			
			// aapt resource value: 0x7f060039
			public const int spinner1 = 2131099705;
			
			// aapt resource value: 0x7f060043
			public const int students = 2131099715;
			
			// aapt resource value: 0x7f060001
			public const int tableLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int tableRow1 = 2131099651;
			
			// aapt resource value: 0x7f060023
			public const int tableRow10 = 2131099683;
			
			// aapt resource value: 0x7f060026
			public const int tableRow11 = 2131099686;
			
			// aapt resource value: 0x7f060029
			public const int tableRow12 = 2131099689;
			
			// aapt resource value: 0x7f06002c
			public const int tableRow13 = 2131099692;
			
			// aapt resource value: 0x7f06002f
			public const int tableRow14 = 2131099695;
			
			// aapt resource value: 0x7f060032
			public const int tableRow15 = 2131099698;
			
			// aapt resource value: 0x7f060020
			public const int tableRow16 = 2131099680;
			
			// aapt resource value: 0x7f060006
			public const int tableRow2 = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int tableRow3 = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int tableRow4 = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int tableRow5 = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int tableRow6 = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int tableRow7 = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int tableRow8 = 2131099673;
			
			// aapt resource value: 0x7f06001d
			public const int tableRow9 = 2131099677;
			
			// aapt resource value: 0x7f060044
			public const int teachers = 2131099716;
			
			// aapt resource value: 0x7f060040
			public const int text = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int textView1 = 2131099713;
			
			// aapt resource value: 0x7f060004
			public const int textView51 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int textView52 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int textView53 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int textView54 = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int textView55 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int textView56 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int textView57 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int textView58 = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int textView59 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int textView60 = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int textView61 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int textView62 = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int textView63 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int textView64 = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int textView65 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int textView66 = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int textView67 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int textView68 = 2131099679;
			
			// aapt resource value: 0x7f060027
			public const int textView69 = 2131099687;
			
			// aapt resource value: 0x7f060025
			public const int textView70 = 2131099685;
			
			// aapt resource value: 0x7f06002d
			public const int textView71 = 2131099693;
			
			// aapt resource value: 0x7f06002b
			public const int textView72 = 2131099691;
			
			// aapt resource value: 0x7f060030
			public const int textView73 = 2131099696;
			
			// aapt resource value: 0x7f06002e
			public const int textView74 = 2131099694;
			
			// aapt resource value: 0x7f060033
			public const int textView75 = 2131099699;
			
			// aapt resource value: 0x7f060031
			public const int textView76 = 2131099697;
			
			// aapt resource value: 0x7f060024
			public const int textView85 = 2131099684;
			
			// aapt resource value: 0x7f060022
			public const int textView86 = 2131099682;
			
			// aapt resource value: 0x7f06002a
			public const int textView87 = 2131099690;
			
			// aapt resource value: 0x7f060028
			public const int textView88 = 2131099688;
			
			// aapt resource value: 0x7f060002
			public const int textView90 = 2131099650;
			
			// aapt resource value: 0x7f06001c
			public const int textView91 = 2131099676;
			
			// aapt resource value: 0x7f06000c
			public const int textView92 = 2131099660;
			
			// aapt resource value: 0x7f060034
			public const int textView94 = 2131099700;
			
			// aapt resource value: 0x7f060021
			public const int textView95 = 2131099681;
			
			// aapt resource value: 0x7f06003c
			public const int toDate = 2131099708;
			
			// aapt resource value: 0x7f06003a
			public const int today = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int tomorrow = 2131099707;
			
			// aapt resource value: 0x7f060042
			public const int type = 2131099714;
			
			// aapt resource value: 0x7f060037
			public const int viewSwitcher1 = 2131099703;
			
			// aapt resource value: 0x7f060036
			public const int viewSwitcherMain = 2131099702;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int bells = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Settings = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int actionbar = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int popup = 2131034113;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
	}
}
#pragma warning restore 1591
