#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("lessons.Resource", IsApplication=true)]

namespace lessons
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int group_codes = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int groups = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_overflow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070014
			public const int about = 2131165204;
			
			// aapt resource value: 0x7f070016
			public const int bells = 2131165206;
			
			// aapt resource value: 0x7f070008
			public const int datePicker = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int main = 2131165187;
			
			// aapt resource value: 0x7f070015
			public const int overflow = 2131165205;
			
			// aapt resource value: 0x7f070011
			public const int radioButton1 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int radioButton2 = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int radioGroup1 = 2131165200;
			
			// aapt resource value: 0x7f070009
			public const int rasp = 2131165193;
			
			// aapt resource value: 0x7f070013
			public const int saveForToday = 2131165203;
			
			// aapt resource value: 0x7f07000b
			public const int settings = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int spinner1 = 2131165188;
			
			// aapt resource value: 0x7f07000e
			public const int students = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int teachers = 2131165199;
			
			// aapt resource value: 0x7f07000a
			public const int text = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int textView1 = 2131165196;
			
			// aapt resource value: 0x7f070007
			public const int toDate = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int today = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int tomorrow = 2131165190;
			
			// aapt resource value: 0x7f07000d
			public const int type = 2131165197;
			
			// aapt resource value: 0x7f070002
			public const int viewSwitcher1 = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int viewSwitcherMain = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int actionbar = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int popup = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
